"""Extract a CLICK PLC .ckp project file into its constituent parts.

Two CKP container variants are supported:

  Variant A ("vPt" / older EB Pro):
      magic       'vPt\\0'
      first sec   SC-PRJ at 0x074
      per-sec hdr 00 00 50 03 00 00
      contains    SC-PRJ, SC-INI, SC-DVIEW, SC-CMORE, SC-SCR x N
                  + 3 trailing zip blobs (zip1/zip2 = node-RED+OPC-UA,
                  zip3 = password-protected scp.bin.zi cache of SC_.mdb)

  Variant B (new EB Pro):
      magic       four-byte version marker (e.g. ac 72 5c 00)
      first sec   SC-PRJ at 0x05c
      per-sec hdr 00 00 28 03 00 00
      contains    SC-PRJ, SC-INI, SC-NICK, SC-DVIEW, SC-CMORE, SC-SCR x N
                  - no scp.bin.zi.  SC_.mdb is regenerated by EB Pro from
                  the SC-* sections into a temp folder when the project opens.

Section bodies (same in both variants):
  SC-PRJ    project metadata (often empty)
  SC-INI    one length-prefixed UTF-16LE filename + LE length + raw text
  SC-NICK   tag nicknames (variant B only)
  SC-DVIEW  list of data-view filenames (UTF-16LE pstrs)
  SC-CMORE  CSV tag dictionary  (LE length at +0x40, then ASCII CSV)
  SC-SCR    ladder logic for one subroutine
"""

import io
import os
import re
import struct
import sys
import zipfile


def u16(data, off): return struct.unpack_from('<H', data, off)[0]
def u32(data, off): return struct.unpack_from('<I', data, off)[0]


def parse_header(data):
    """Decode the section table.  Same field layout in both variants — only
    the magic byte and the SC-PRJ start position differ:

        0x00  4-byte magic (variant A: 'vPt\\0'; variant B: e.g. ac 72 5c 00)
        0x04  reserved (2 bytes)
        0x06  SC-PRJ size
        0x0a  SC-INI  offset
        0x0e  SC-INI  size
        0x12  SC-NICK offset (variant B; 0 in A)
        0x16  SC-NICK size   (variant B; 0 in A)
        0x1a  SC-DVIEW offset
        0x1e  SC-DVIEW size
        0x22  SC-CMORE offset
        0x26  SC-CMORE size
        0x2a  subroutine count (u16) | 2-byte pad
        0x2c  SCR slots: (offset, size) x N
        ...
        0x5c  zip1 offset (variant A only)
        0x60  zip1 size
        0x64  zip2 offset
        0x68  zip2 size
        0x6c  zip3 offset
        0x70  zip3 size
    """
    if data[:4] == b'vPt\x00':
        variant = 'A'
        prj_off = 0x74
    else:
        variant = 'B'
        prj_off = 0x5c
    sub_count = u16(data, 0x2a)
    scr_slots = []
    for i in range(sub_count):
        off = u32(data, 0x2c + 8 * i)
        sz  = u32(data, 0x30 + 8 * i)
        if off and sz:
            scr_slots.append((off, sz))
    h = {
        "variant": variant,
        "prj":   (prj_off,          u32(data, 0x06)),
        "ini":   (u32(data, 0x0a),  u32(data, 0x0e)),
        "nick":  (u32(data, 0x12),  u32(data, 0x16)),
        "dview": (u32(data, 0x1a),  u32(data, 0x1e)),
        "cmore": (u32(data, 0x22),  u32(data, 0x26)),
        "sub_count": sub_count,
        "scr":   scr_slots,
    }
    if variant == 'A':
        h.update({
            "zip1": (u32(data, 0x5c), u32(data, 0x60)),
            "zip2": (u32(data, 0x64), u32(data, 0x68)),
            "zip3": (u32(data, 0x6c), u32(data, 0x70)),
        })
    return h


def read_pstr_utf16(data, off):
    """1-byte length-prefixed UTF-16LE string (length includes the prefix byte)."""
    n = data[off]
    return data[off+1:off+n].decode('utf-16-le', errors='replace').rstrip('\x00')


def extract_ini(data, off, size):
    """SC-INI body: UTF-16LE filename, then 4-byte LE content length, then raw bytes."""
    p = off + 0x40
    fn_len = data[p]
    fn = data[p+1:p+fn_len].decode('utf-16-le').rstrip('\x00')
    p = p + fn_len + 1            # skip pstr null pair
    content_len = u32(data, p)
    body = data[p+4:p+4+content_len]
    return fn, body


def extract_dview(data, off, size):
    """List of UTF-16LE pstrs in DVIEW. We only emit non-empty entries."""
    end = off + size
    p = off + 0x40
    files = []
    while p < end:
        n = data[p]
        if n == 0:
            p += 1; continue
        if n < 0x05 or n > 0x40 or p + n > end:
            p += 1; continue
        try:
            s = data[p+1:p+n].decode('utf-16-le').rstrip('\x00')
        except Exception:
            p += 1; continue
        if s.isprintable() and any(c in s for c in ('.', '/')):
            files.append(s)
        p += n
    return files


def extract_cmore(data, off, size):
    """SC-CMORE body: 4-byte LE length at +0x40, then CSV ASCII text."""
    p = off + 0x40
    csv_len = u32(data, p)
    return data[p+4:p+4+csv_len].decode('utf-8')


# Ladder logic (from earlier work)
LADDER_OPCODES = {
    0x11: "ContactNO", 0x12: "ContactNC", 0x15: "Out",
    0x23: "Call", 0x24: "Return", 0x27: "End",
}
TAGGED = {0x11, 0x12, 0x15}
RUNG_MARKER = re.compile(rb'\x20\x00(?:\x01[\x00-\x1f]){32}')


def parse_scr(data, off, size):
    end = off + size
    sub_id = u16(data, off + 0x40)
    sub_name = read_pstr_utf16(data, off + 0x42)
    breaks = [m.end() for m in RUNG_MARKER.finditer(data, off, end)]
    rungs = []
    for a, b in zip([off] + breaks, breaks + [end]):
        instrs = []
        p = a
        while p < b - 2:
            ln = data[p]
            if ln in (0x07, 0x09, 0x0d, 0x13) and p + ln + 4 < b:
                try:
                    nm = data[p+1:p+ln].decode('utf-16-le').rstrip('\x00')
                except Exception:
                    p += 1; continue
                if nm not in LADDER_OPCODES.values():
                    p += 1; continue
                op_off = p + ln + 1
                op = data[op_off]
                if op not in LADDER_OPCODES:
                    p += 1; continue
                tag = None
                if op in TAGGED:
                    tlen_off = op_off + 16
                    tlen = data[tlen_off]
                    if tlen and tlen_off + tlen < b:
                        try:
                            tag = data[tlen_off+1:tlen_off+tlen].decode('utf-16-le').rstrip('\x00')
                        except Exception:
                            pass
                elif op == 0x23:
                    for q in range(op_off + 17, min(op_off + 60, b)):
                        tl = data[q]
                        if tl in (9, 0x0d, 0x13, 0x19, 0x21, 0x29):
                            try:
                                t = data[q+1:q+tl].decode('utf-16-le').rstrip('\x00')
                                if t and t.isprintable():
                                    tag = t; break
                            except Exception:
                                pass
                instrs.append((op, LADDER_OPCODES[op], tag))
                p = op_off + 1
            else:
                p += 1
        if instrs:
            rungs.append(instrs)
    return sub_id, sub_name, rungs


def render_rung(instrs):
    contacts, outputs = [], []
    for op, _, tag in instrs:
        if op == 0x11:    contacts.append(tag)
        elif op == 0x12:  contacts.append(f"NOT {tag}")
        elif op == 0x15:  outputs.append(f"COIL({tag})")
        elif op == 0x23:  outputs.append(f"CALL {tag}")
        elif op == 0x24:  outputs.append("RETURN")
        elif op == 0x27:  outputs.append("END")
    lhs = " AND ".join(contacts)
    rhs = " ; ".join(outputs)
    if lhs and rhs:  return f"{lhs}  ->  {rhs}"
    return rhs or lhs or "(empty)"


def main(ckp_path, out_dir):
    data = open(ckp_path, 'rb').read()
    h = parse_header(data)
    os.makedirs(out_dir, exist_ok=True)

    # SC-INI
    fn, body = extract_ini(data, *h['ini'])
    open(os.path.join(out_dir, fn), 'wb').write(body)
    print(f"  wrote {fn}  ({len(body)} bytes)")

    # SC-DVIEW
    dview = extract_dview(data, *h['dview'])
    open(os.path.join(out_dir, 'DataView.list'), 'w').write("\n".join(dview) + "\n")
    print(f"  wrote DataView.list  ({len(dview)} filenames)")

    # SC-CMORE (CSV tag dictionary)
    csv = extract_cmore(data, *h['cmore'])
    open(os.path.join(out_dir, 'tags.csv'), 'w').write(csv)
    print(f"  wrote tags.csv  ({csv.count(chr(10))} lines)")

    # SC-SCR ladder (one section per subroutine)
    program_lines = ["# Decoded ladder logic"]
    for off, size in h['scr']:
        sub_id, sub_name, rungs = parse_scr(data, off, size)
        program_lines.append(f"\nSubroutine #{sub_id}: {sub_name}")
        for i, ins in enumerate(rungs, 1):
            program_lines.append(f"  Rung {i}: {render_rung(ins)}")
    open(os.path.join(out_dir, 'program.txt'), 'w').write("\n".join(program_lines) + "\n")
    print(f"  wrote program.txt")

    # SC-NICK (variant B only) — tag nicknames + memory references.
    # Format: per-entry the section holds 2 or 4 length-prefixed UTF-16LE strings:
    #   (type, number)            for memory references with no nickname
    #   (type, number, nick, dfl) for user/system tags with non-default values
    # Each pstr is `len_byte + len_byte_value bytes` (last byte is the trailing
    # 0x00 of the UTF-16LE null terminator).  Entries are separated by a few
    # bytes of header that we skip by scanning.
    if h['nick'][1]:
        off, size = h['nick']
        nick_strs = []
        i = off + 0x40
        end = off + size
        while i < end - 1:
            n = data[i]
            if n < 3 or n > 0x40 or n % 2 == 0 or i + 1 + n > end:
                i += 1; continue
            try:
                s = data[i+1:i+n].decode('utf-16-le').rstrip('\x00')
            except Exception:
                i += 1; continue
            if s and all(0x20 <= ord(c) < 0x7f for c in s):
                nick_strs.append(s)
                i += 1 + n
            else:
                i += 1
        rows = []
        j = 0
        while j + 1 < len(nick_strs):
            addr = nick_strs[j] + nick_strs[j+1]
            if j + 2 < len(nick_strs) and nick_strs[j+2].startswith('_'):
                nick = nick_strs[j+2]
                default = nick_strs[j+3] if j + 3 < len(nick_strs) else ''
                j += 4
            else:
                nick = default = ''
                j += 2
            rows.append((addr, nick, default))
        with open(os.path.join(out_dir, 'nicknames.csv'), 'w') as f:
            f.write("address,nickname,default\n")
            for addr, nick, default in rows:
                f.write(f"{addr},{nick},{default}\n")
        print(f"  wrote nicknames.csv  ({len(rows)} entries)")

    # Three trailing zips (variant A only)
    if h['variant'] != 'A':
        return
    for name in ('zip1', 'zip2', 'zip3'):
        off, size = h[name]
        blob = data[off:off+size]
        open(os.path.join(out_dir, f"{name}.zip"), 'wb').write(blob)
        zf = zipfile.ZipFile(io.BytesIO(blob))
        sub_dir = os.path.join(out_dir, name)
        os.makedirs(sub_dir, exist_ok=True)
        for info in zf.infolist():
            if info.is_dir():
                continue
            if info.flag_bits & 1:
                # encrypted -> can't extract; emit a marker file with the metadata
                marker = (
                    f"ENCRYPTED PKZIP entry\n"
                    f"  filename:    {info.filename}\n"
                    f"  uncompressed:{info.file_size}\n"
                    f"  compressed:  {info.compress_size}\n"
                    f"  CRC32:       {info.CRC:#010x}\n"
                    f"  encryption:  PKZIP traditional (ZipCrypto)\n"
                )
                target = os.path.join(sub_dir, info.filename + '.encrypted')
                os.makedirs(os.path.dirname(target) or sub_dir, exist_ok=True)
                open(target + '.info', 'w').write(marker)
                print(f"  ! {name}/{info.filename}: encrypted, wrote .info marker only")
            else:
                target = os.path.join(sub_dir, info.filename)
                os.makedirs(os.path.dirname(target) or sub_dir, exist_ok=True)
                open(target, 'wb').write(zf.read(info.filename))
                print(f"  wrote {name}/{info.filename}")

    # If any of zip1/zip2's inner zip wraps still need recursive unwrap, do it.
    # The user's archive contains scp.bin.zi nested in zip3 which is itself a
    # zip wrapping SC_.mdb -- but it's encrypted so we can't recurse here.


if __name__ == "__main__":
    ckp = sys.argv[1] if len(sys.argv) > 1 else "demo/ClickTest.ckp"
    out = sys.argv[2] if len(sys.argv) > 2 else "demo/extracted"
    main(ckp, out)
